/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ransomware;

/**
 *
 * @author H P
 */
public class AboutMe extends javax.swing.JFrame {

    /**
     * Creates new form Warning
     */
    public AboutMe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_bubble = new javax.swing.JLabel();
        lbl_line1 = new javax.swing.JLabel();
        lbl_line3 = new javax.swing.JLabel();
        lbl_line4 = new javax.swing.JLabel();
        lbl_line5 = new javax.swing.JLabel();
        btn_create = new javax.swing.JButton();
        lbl_line6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(57, 73, 171));
        jPanel1.setLayout(null);

        lbl_bubble.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 24)); // NOI18N
        lbl_bubble.setForeground(new java.awt.Color(3, 169, 244));
        lbl_bubble.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_bubble.setText("About Me");
        jPanel1.add(lbl_bubble);
        lbl_bubble.setBounds(40, 20, 240, 30);

        lbl_line1.setBackground(new java.awt.Color(156, 39, 176));
        lbl_line1.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 16)); // NOI18N
        lbl_line1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_line1.setText("Assignment  :   02 (Cryptography)");
        jPanel1.add(lbl_line1);
        lbl_line1.setBounds(35, 190, 260, 38);

        lbl_line3.setBackground(new java.awt.Color(156, 39, 176));
        lbl_line3.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 16)); // NOI18N
        lbl_line3.setForeground(new java.awt.Color(255, 255, 255));
        lbl_line3.setText("ID                   :   IT15127174");
        jPanel1.add(lbl_line3);
        lbl_line3.setBounds(35, 70, 260, 38);

        lbl_line4.setBackground(new java.awt.Color(156, 39, 176));
        lbl_line4.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 16)); // NOI18N
        lbl_line4.setForeground(new java.awt.Color(255, 255, 255));
        lbl_line4.setText("Batch             :   Weekday");
        jPanel1.add(lbl_line4);
        lbl_line4.setBounds(35, 150, 260, 38);

        lbl_line5.setBackground(new java.awt.Color(156, 39, 176));
        lbl_line5.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 16)); // NOI18N
        lbl_line5.setForeground(new java.awt.Color(255, 255, 255));
        lbl_line5.setText("Name            :   Ranasinghe R.A.N.I");
        jPanel1.add(lbl_line5);
        lbl_line5.setBounds(35, 110, 260, 38);

        btn_create.setBackground(new java.awt.Color(3, 169, 244));
        btn_create.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        btn_create.setForeground(new java.awt.Color(255, 255, 255));
        btn_create.setText("OK");
        btn_create.setBorder(null);
        btn_create.setBorderPainted(false);
        btn_create.setContentAreaFilled(false);
        btn_create.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_create.setOpaque(true);
        btn_create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_createActionPerformed(evt);
            }
        });
        jPanel1.add(btn_create);
        btn_create.setBounds(90, 310, 110, 28);

        lbl_line6.setBackground(new java.awt.Color(156, 39, 176));
        lbl_line6.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 16)); // NOI18N
        lbl_line6.setForeground(new java.awt.Color(255, 255, 255));
        lbl_line6.setText("Module         : Secure Software Systems");
        jPanel1.add(lbl_line6);
        lbl_line6.setBounds(35, 230, 280, 38);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 330, 390);

        setSize(new java.awt.Dimension(326, 388));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_createActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_createActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AboutMe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AboutMe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AboutMe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AboutMe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AboutMe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_create;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_bubble;
    private javax.swing.JLabel lbl_line1;
    private javax.swing.JLabel lbl_line3;
    private javax.swing.JLabel lbl_line4;
    private javax.swing.JLabel lbl_line5;
    private javax.swing.JLabel lbl_line6;
    // End of variables declaration//GEN-END:variables
}
