
package ransomware;

import javafx.scene.paint.Color;


public class Answer extends javax.swing.JFrame {
    
    boolean successStatus = false;
    String folderPath = "";
    
    public Answer() {
        initComponents();
        
    }
    
    public Answer(boolean status, String pfolderPath){
        initComponents();
        
        successStatus = status;
        folderPath = pfolderPath;
       
        if (successStatus == false) {
            lbl_warning.setVisible(false);
            lbl_warning2.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btn_ok = new javax.swing.JButton();
        lbl_warning = new javax.swing.JLabel();
        lbl_warning2 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(21, 101, 192));
        jPanel2.setLayout(null);

        jPanel1.setBackground(new java.awt.Color(30, 136, 229));
        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Leelawadee UI", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Look for selected folder to view your answer!");
        jLabel3.setToolTipText("");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 40, 360, 30);

        btn_ok.setBackground(new java.awt.Color(29, 96, 229));
        btn_ok.setFont(new java.awt.Font("Leelawadee UI", 0, 16)); // NOI18N
        btn_ok.setForeground(new java.awt.Color(255, 255, 255));
        btn_ok.setText("OK");
        btn_ok.setBorderPainted(false);
        btn_ok.setContentAreaFilled(false);
        btn_ok.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_ok.setOpaque(true);
        btn_ok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_okMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_okMouseExited(evt);
            }
        });
        btn_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_okActionPerformed(evt);
            }
        });
        jPanel1.add(btn_ok);
        btn_ok.setBounds(120, 100, 100, 40);

        lbl_warning.setFont(new java.awt.Font("Leelawadee UI", 0, 20)); // NOI18N
        lbl_warning.setForeground(new java.awt.Color(255, 23, 68));
        lbl_warning.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_warning.setText("***Your first text file of selected folder ");
        lbl_warning.setToolTipText("");
        jPanel1.add(lbl_warning);
        lbl_warning.setBounds(10, 150, 340, 30);

        lbl_warning2.setFont(new java.awt.Font("Leelawadee UI", 0, 20)); // NOI18N
        lbl_warning2.setForeground(new java.awt.Color(255, 23, 68));
        lbl_warning2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_warning2.setText("  was encrypted..! :P");
        lbl_warning2.setToolTipText("");
        jPanel1.add(lbl_warning2);
        lbl_warning2.setBounds(10, 180, 340, 30);

        jPanel2.add(jPanel1);
        jPanel1.setBounds(10, 10, 350, 225);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 370, 245);

        setSize(new java.awt.Dimension(369, 245));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_okMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_okMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_okMouseEntered

    private void btn_okMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_okMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_okMouseExited

    private void btn_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_okActionPerformed
        this.dispose();
        if (successStatus == true) {
            DecryptionForm df = new DecryptionForm(folderPath);
            df.setVisible(true);
            
        }
    }//GEN-LAST:event_btn_okActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Answer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Answer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Answer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Answer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Answer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ok;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbl_warning;
    private javax.swing.JLabel lbl_warning2;
    // End of variables declaration//GEN-END:variables
}
