
package ransomware;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FilenameFilter;
import java.security.spec.KeySpec;
import java.util.StringTokenizer;
import javax.crypto.Cipher;
import javax.crypto.SecretKey;
import javax.crypto.SecretKeyFactory;
import javax.crypto.spec.IvParameterSpec;
import javax.crypto.spec.PBEKeySpec;
import javax.crypto.spec.SecretKeySpec;
import javax.swing.JOptionPane;


public class DecryptionForm extends javax.swing.JFrame {
    
    String folderPath = "";
  
    
    public DecryptionForm() {
        initComponents();
        lbl_about.setVisible(false);
        lbl_close.setVisible(false);
    }
    
    public DecryptionForm(String pfolderPath) {
        initComponents();
        lbl_about.setVisible(false);
        lbl_close.setVisible(false);
        
        folderPath = pfolderPath;
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lbl_close = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        lbl_closepic = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbl_about = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txt_key = new javax.swing.JTextField();
        btn_decrypt = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(30, 136, 229));
        jPanel1.setLayout(null);

        lbl_close.setBackground(new java.awt.Color(195, 75, 215));
        lbl_close.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 16)); // NOI18N
        lbl_close.setForeground(new java.awt.Color(178, 178, 178));
        lbl_close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_close.setText("Close");
        jPanel1.add(lbl_close);
        lbl_close.setBounds(500, 30, 90, 20);

        jPanel2.setBackground(new java.awt.Color(25, 118, 210));
        jPanel2.setLayout(null);

        jPanel4.setBackground(new java.awt.Color(21, 101, 192));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel4MouseExited(evt);
            }
        });
        jPanel4.setLayout(null);

        lbl_closepic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_closepic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ransomware/ic_highlight_off_white_24dp_1x.png"))); // NOI18N
        lbl_closepic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_closepicMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_closepicMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_closepicMouseExited(evt);
            }
        });
        jPanel4.add(lbl_closepic);
        lbl_closepic.setBounds(10, 10, 30, 30);

        jPanel2.add(jPanel4);
        jPanel4.setBounds(550, 0, 50, 50);

        jLabel1.setFont(new java.awt.Font("Leelawadee UI", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DECRYPT YOUR FILES");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(190, 10, 220, 30);

        lbl_about.setBackground(new java.awt.Color(195, 75, 215));
        lbl_about.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 16)); // NOI18N
        lbl_about.setForeground(new java.awt.Color(178, 178, 178));
        lbl_about.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_about.setText("About Me");
        jPanel2.add(lbl_about);
        lbl_about.setBounds(20, 30, 90, 20);

        jPanel9.setBackground(new java.awt.Color(21, 101, 192));
        jPanel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel9MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel9MouseExited(evt);
            }
        });
        jPanel9.setLayout(null);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ransomware/ic_person_white_24dp_1x.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel5MouseExited(evt);
            }
        });
        jPanel9.add(jLabel5);
        jLabel5.setBounds(10, 10, 30, 30);

        jPanel2.add(jPanel9);
        jPanel9.setBounds(0, 0, 50, 50);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 600, 50);

        jPanel5.setBackground(new java.awt.Color(30, 136, 229));
        jPanel5.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Leelawadee UI", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Enter key :");
        jLabel3.setToolTipText("");
        jPanel5.add(jLabel3);
        jLabel3.setBounds(40, 40, 110, 30);

        txt_key.setFont(new java.awt.Font("Leelawadee UI", 0, 16)); // NOI18N
        txt_key.setFocusCycleRoot(true);
        txt_key.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_keyActionPerformed(evt);
            }
        });
        jPanel5.add(txt_key);
        txt_key.setBounds(160, 40, 410, 30);

        btn_decrypt.setBackground(new java.awt.Color(29, 96, 229));
        btn_decrypt.setFont(new java.awt.Font("Leelawadee UI", 0, 16)); // NOI18N
        btn_decrypt.setForeground(new java.awt.Color(255, 255, 255));
        btn_decrypt.setText("Decrypt");
        btn_decrypt.setBorderPainted(false);
        btn_decrypt.setContentAreaFilled(false);
        btn_decrypt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_decrypt.setOpaque(true);
        btn_decrypt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_decryptMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_decryptMouseExited(evt);
            }
        });
        btn_decrypt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_decryptActionPerformed(evt);
            }
        });
        jPanel5.add(btn_decrypt);
        btn_decrypt.setBounds(240, 110, 110, 50);

        jLabel6.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jLabel6.setText("*****Search for the passwordFile.txt in previously selected directory to find the decryption key");
        jLabel6.setToolTipText("");
        jPanel5.add(jLabel6);
        jLabel6.setBounds(10, 190, 580, 40);

        jPanel1.add(jPanel5);
        jPanel5.setBounds(0, 50, 600, 230);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 600, 280);

        setSize(new java.awt.Dimension(600, 280));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        new AboutMe().setVisible(true);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered
        lbl_about.setVisible(true);
    }//GEN-LAST:event_jLabel5MouseEntered

    private void jLabel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseExited
        lbl_about.setVisible(false);
    }//GEN-LAST:event_jLabel5MouseExited

    private void jPanel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel9MouseClicked
        new AboutMe().setVisible(true);
    }//GEN-LAST:event_jPanel9MouseClicked

    private void jPanel9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel9MouseEntered
        lbl_about.setVisible(true);
    }//GEN-LAST:event_jPanel9MouseEntered

    private void jPanel9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel9MouseExited
        lbl_about.setVisible(false);
    }//GEN-LAST:event_jPanel9MouseExited

    private void lbl_closepicMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_closepicMouseClicked
        this.dispose();
    }//GEN-LAST:event_lbl_closepicMouseClicked

    private void lbl_closepicMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_closepicMouseEntered
        lbl_close.setVisible(true);
    }//GEN-LAST:event_lbl_closepicMouseEntered

    private void lbl_closepicMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_closepicMouseExited
        lbl_close.setVisible(false);
    }//GEN-LAST:event_lbl_closepicMouseExited

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
        this.dispose();
    }//GEN-LAST:event_jPanel4MouseClicked

    private void jPanel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseEntered
        lbl_close.setVisible(true);
    }//GEN-LAST:event_jPanel4MouseEntered

    private void jPanel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseExited
        
        lbl_close.setVisible(false);
        
    }//GEN-LAST:event_jPanel4MouseExited

    private void txt_keyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_keyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_keyActionPerformed

    private void btn_decryptMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_decryptMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_decryptMouseEntered

    private void btn_decryptMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_decryptMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_decryptMouseExited

    private void btn_decryptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_decryptActionPerformed
            
        try{
            
            //-----specify password
            String password = "nimz@123456789";
            System.out.println(password);
                
            
            //------see whether the key text field is empty or user input key values is valid or not
            if (!txt_key.getText().equals(password)) {                
                JOptionPane.showMessageDialog(this, "Enter the a valid DECRYPTION KEY!", "Error!", JOptionPane.ERROR_MESSAGE);
                txt_key.setText("");
            }            
            else{ //**************file Dencryption part*******************
                //********************************************************
                
                //-----search for the .des files in the user selected directory---------
                String filename = "";                           //variable to store file name with the extension
                File dir = new File(folderPath);                       //specify the selected

                    //get the list of file names ends with .txt extension
                FilenameFilter filter = new FilenameFilter() {
                    public boolean accept (File dir, String name) { 
                        return name.endsWith(".des");
                    } 
                }; 
                String[] children = dir.list(filter);
                    //get the file name from files list
                if (children == null) {
                    System.out.println("Either dir does not exist or is not a directory"); 
                } 
                else {
                    if (0 < children.length) {
                        filename = children[0];
                        System.out.println(filename);
                    } 
                } 



                String fileNameWOExtension = "";                     //variable to store file name without extension

                //-----get the file name only by eleminating .des extension-----------
                StringTokenizer fnameFull = new StringTokenizer(filename, ".");        
                int tokenCount = 0;
                while (fnameFull.hasMoreTokens() && fnameFull.countTokens()>1) {
                    if (tokenCount > 0) {               //if file nae has multiple dots
                        fileNameWOExtension = fileNameWOExtension + "." + fnameFull.nextToken();
                    }
                    else {
                        fileNameWOExtension = fnameFull.nextToken();
                    }
                    System.out.println(fileNameWOExtension + "  " + tokenCount);
                    tokenCount++;
                }

            
                        
            
                //-----reading the salt-----------------------------------
                // user should have secure mechanism to transfer the
                // salt, iv and password to the recipient
                FileInputStream saltFis = new FileInputStream(folderPath + "\\salt.enc");
                byte[] salt = new byte[8];
                saltFis.read(salt);
                saltFis.close();

                //-----reading the iv---------------------------------------
                FileInputStream ivFis = new FileInputStream(folderPath + "\\iv.enc");
                byte[] iv = new byte[16];
                ivFis.read(iv);
                ivFis.close();
               
                //-----generate the key------------------------------------------
                SecretKeyFactory factory = SecretKeyFactory.getInstance("PBKDF2WithHmacSHA1");
                KeySpec keySpec = new PBEKeySpec(password.toCharArray(), salt, 65536, 256);
                SecretKey tmp = factory.generateSecret(keySpec);
                SecretKey secret = new SecretKeySpec(tmp.getEncoded(), "AES");
                System.out.println(secret.toString());

                //-----dencrypt the file with the generated dkey----------------
                Cipher cipher = Cipher.getInstance("AES/CBC/PKCS5Padding");
                cipher.init(Cipher.DECRYPT_MODE, secret, new IvParameterSpec(iv));
            
                FileInputStream fis = new FileInputStream(folderPath + "\\" + filename);
                FileOutputStream fos = new FileOutputStream(folderPath + "\\" + fileNameWOExtension + ".txt");
            
                byte[] in = new byte[64];
                int read;
            
                while ((read = fis.read(in)) != -1) {
                        byte[] output = cipher.update(in, 0, read);
                        if (output != null)
                                fos.write(output);
                }

                byte[] output = cipher.doFinal();
                if (output != null)
                        fos.write(output);
                fis.close();
                fos.flush();
                fos.close();
                System.out.println("File Decrypted.");
            
                //-----delete .des file---------------------------------------
                boolean fdelete = new File(folderPath + "\\" + filename).delete();

                if (fdelete) {
                    System.out.println("file deleted");
                }

                //********decryption done******************
                
                JOptionPane.showMessageDialog(this, "Cheers..! \nYour files were decrypted", "Done!", JOptionPane.INFORMATION_MESSAGE);
            
                this.dispose();
                
            }
            
        }
        catch(NullPointerException e){
            JOptionPane.showMessageDialog(this, "Fill the text Feilds correctly..!", "Error!", JOptionPane.WARNING_MESSAGE);
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Fill the text Feilds correctly..!", "Error!", JOptionPane.WARNING_MESSAGE);
        }
        catch(Exception e){
//            System.out.println(e);
            JOptionPane.showMessageDialog(this, "Error..!", "Error!", JOptionPane.ERROR_MESSAGE);
            
        }
        
               
    }//GEN-LAST:event_btn_decryptActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DecryptionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DecryptionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DecryptionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DecryptionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DecryptionForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_decrypt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lbl_about;
    private javax.swing.JLabel lbl_close;
    private javax.swing.JLabel lbl_closepic;
    private javax.swing.JTextField txt_key;
    // End of variables declaration//GEN-END:variables
}
